"""second migration

Revision ID: 9cc0dd1c9687
Revises: b4cb7cdfa080
Create Date: 2023-09-28 21:42:11.885743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cc0dd1c9687'
down_revision: Union[str, None] = 'b4cb7cdfa080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('word', 'score',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('word', 'is_exposed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('word', 'is_memorized',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('word', 'half_life_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('word', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('test', sa.INTEGER(), nullable=False))
    op.alter_column('word', 'half_life_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('word', 'is_memorized',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('word', 'is_exposed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('word', 'score',
               existing_type=sa.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
