"""Initial migration

Revision ID: b4cb7cdfa080
Revises: c78be8da24d2
Create Date: 2023-09-28 15:50:33.352009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4cb7cdfa080'
down_revision: Union[str, None] = 'c78be8da24d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('test', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word', 'test')
    # ### end Alembic commands ###
